default: &default
  adapter: postgresql
  encoding: unicode
  # RUNNING app on docker
  host: <%= ENV.fetch("DATABASE_HOST", nil) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", nil) %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", nil) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: freelacrm_development

test:
  <<: *default
  database: freelacrm_test

production:
  <<: *default
  database: freelacrm_production
